## The functions below are examples of functions that 1)can create special objects that belong to 
# different environment and can cashe some of its values 2) can compute some of that special objects values, 
# prior to which it checkes if those values are cashed


## makeCasheMatrix - creates 'matrix' object that can cashe its invers


makeCacheMatrix <- function(x = matrix()) {
    inv<-NULL
    set<- function (y){
        x<<-y
        inve<<-NULL
    }
    get<-function() x
    setinv<-function(inverse) inv<<-inverse
    getinv<-function () inv
    list(set=set, get=get, setinv=setinv, getinv=getinv)
}


## casheSolve - calculates inverse of special matrix that is generated by the above function, 
## prior to calculation the function looks up if the inverse values is already cashed to avoid calculating it again

cacheSolve <- function(x, ...) {
    inv<-x$getinv()
    if(!is.null(inv)){
        message('getting cashed inverse value')
        return(inv)
    }
    data<-x$get()
    inv<-solve(data,...)
    x$setinv(inv)
    inv
}
